EVALUATE
TOPN(
    12,
    CALCULATETABLE(
        SUMMARIZECOLUMNS(
            'Claims'[Claim ID],
            'Customer'[Customer ID],
            'Customer'[Customer Name],
            'Claim Type'[Claim Type Name],
            'Claims'[Claim Status],
            'Claims'[Claim Date],
            "Amount", [Total Claim Amount]
        ),
        'Claims'[Claim Status] = "Open"
    ),
    [Amount], DESC
)
ORDER BY [Amount] DESC
